"""Backward-compatible re-exports.

The schema definitions have been split by domain into sibling modules
(``app.schemas.user``, ``app.schemas.track``, ...). Import from here or
directly from the domain module — both paths expose the same names.
"""

from app.schemas.user import (
    UserBase,
    UserCreate,
    RegisterRequest,
    UserRead,
    UserUpdateProfile,
    ChangePasswordRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    DeleteAccountRequest,
    LoginRequest,
    AuthResponse,
    RegisterResponse,
)

from app.schemas.admin import (
    AdminUserUpdate,
    AdminDashboardStats,
    AdminActivityLogEntry,
    AdminOptionalReasonMixin,
    AdminForceStatus,
    AdminReassign,
    AdminReasonPayload,
    AdminTransferOwnershipRequest,
    AdminTrackReopen,
    AdminOptionalReasonPayload,
    AdminReopenDecision,
    AdminReopenRequestEntry,
    AdminAuditLogRead,
    TrackForceStatusRequest,
)

from app.schemas.album import (
    AlbumMemberRead,
    AlbumBase,
    AlbumCreate,
    AlbumMetadataUpdate,
    AlbumTeamUpdate,
    AlbumSummary,
    InvitationCreate,
    InvitationRead,
    AlbumDeadlineUpdate,
    AlbumRead,
    AlbumStats,
    WebhookConfig,
    WebhookDeliveryRead,
)

from app.schemas.circle import (
    CircleMemberRead,
    CircleBase,
    CircleCreate,
    CircleUpdate,
    CircleMemberRoleUpdate,
    CircleRead,
    CircleSummary,
    InviteCodeCreate,
    InviteCodeRead,
    JoinCircleRequest,
)

from app.schemas.track import (
    TrackSourceVersionRead,
    MasterDeliveryRead,
    SourceFollowupRequestRead,
    TrackBase,
    TrackMetadataUpdate,
    AuthorNotesUpdate,
    TrackComposerUpdate,
    TrackExternalComposerRead,
    MasteringNotesUpdate,
    TrackOrderUpdate,
    TrackRead,
    TrackReviewStateRead,
    TrackListItem,
    TrackPlaybackPreferenceRead,
    TrackPlaybackPreferenceUpdate,
    SetPublicRequest,
    TrackDetailResponse,
)

from app.schemas.issue import (
    IssueMarkerCreate,
    IssueMarkerRead,
    IssueBase,
    IssueCreate,
    IssueUpdate,
    IssueAudioRead,
    IssueImageRead,
    IssueRead,
    CommentImageRead,
    CommentAudioRead,
    CommentRead,
    IssueDetail,
    IssueBatchUpdate,
)

from app.schemas.checklist import (
    ChecklistTemplateItem,
    ChecklistTemplateRead,
    ChecklistTemplateUpdate,
    ChecklistItemBase,
    ChecklistItemRead,
    ChecklistSubmit,
    ChecklistDraftRead,
)

from app.schemas.workflow import (
    WorkflowEventRead,
    WorkflowTransitionRequest,
    WorkflowTransitionOption,
    WorkflowStepDefSchema,
    WorkflowConfigSchema,
    StageAssignmentRead,
    ReviewerCandidateRead,
    AssignReviewerRequest,
    ReassignReviewerRequest,
    ReopenRequestCreate,
    DirectReopenRequest,
    ReopenDecisionRequest,
    ReopenRequestRead,
    SourceFollowupDecisionRequest,
    WorkflowTemplateCreate,
    WorkflowTemplateUpdate,
    WorkflowTemplateRead,
)

from app.schemas.notification import (
    NotificationRead,
)

from app.schemas.discussion import (
    DiscussionImageRead,
    DiscussionAudioRead,
    DiscussionRead,
    MentionCandidatesRead,
    DiscussionUpdate,
    CommentUpdate,
    EditHistoryRead,
)

from app.schemas.upload import (
    RequestUploadParams,
    RequestTrackUploadParams,
    PresignedUploadResponse,
    ConfirmUploadParams,
    SourceExternalLinkSubmission,
    ConfirmMasterDeliveryUploadParams,
    ConfirmSourceFollowupUploadParams,
    ConfirmTrackUploadParams,
    RequestCommentAudioUploadParams,
    PresignedCommentAudioResponse,
    AppConfigResponse,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "RegisterRequest",
    "UserRead",
    "UserUpdateProfile",
    "ChangePasswordRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "DeleteAccountRequest",
    "LoginRequest",
    "AuthResponse",
    "RegisterResponse",
    "AdminUserUpdate",
    "AdminDashboardStats",
    "AdminActivityLogEntry",
    "AdminOptionalReasonMixin",
    "AdminForceStatus",
    "AdminReassign",
    "AdminReasonPayload",
    "AdminTransferOwnershipRequest",
    "AdminTrackReopen",
    "AdminOptionalReasonPayload",
    "AdminReopenDecision",
    "AdminReopenRequestEntry",
    "AdminAuditLogRead",
    "TrackForceStatusRequest",
    "AlbumMemberRead",
    "AlbumBase",
    "AlbumCreate",
    "AlbumMetadataUpdate",
    "AlbumTeamUpdate",
    "AlbumSummary",
    "InvitationCreate",
    "InvitationRead",
    "AlbumDeadlineUpdate",
    "AlbumRead",
    "AlbumStats",
    "WebhookConfig",
    "WebhookDeliveryRead",
    "CircleMemberRead",
    "CircleBase",
    "CircleCreate",
    "CircleUpdate",
    "CircleMemberRoleUpdate",
    "CircleRead",
    "CircleSummary",
    "InviteCodeCreate",
    "InviteCodeRead",
    "JoinCircleRequest",
    "TrackSourceVersionRead",
    "MasterDeliveryRead",
    "SourceFollowupRequestRead",
    "TrackBase",
    "TrackMetadataUpdate",
    "AuthorNotesUpdate",
    "TrackComposerUpdate",
    "TrackExternalComposerRead",
    "MasteringNotesUpdate",
    "TrackOrderUpdate",
    "TrackRead",
    "TrackReviewStateRead",
    "TrackListItem",
    "TrackPlaybackPreferenceRead",
    "TrackPlaybackPreferenceUpdate",
    "SetPublicRequest",
    "TrackDetailResponse",
    "IssueMarkerCreate",
    "IssueMarkerRead",
    "IssueBase",
    "IssueCreate",
    "IssueUpdate",
    "IssueAudioRead",
    "IssueImageRead",
    "IssueRead",
    "CommentImageRead",
    "CommentAudioRead",
    "CommentRead",
    "IssueDetail",
    "IssueBatchUpdate",
    "ChecklistTemplateItem",
    "ChecklistTemplateRead",
    "ChecklistTemplateUpdate",
    "ChecklistItemBase",
    "ChecklistItemRead",
    "ChecklistSubmit",
    "ChecklistDraftRead",
    "WorkflowEventRead",
    "WorkflowTransitionRequest",
    "WorkflowTransitionOption",
    "WorkflowStepDefSchema",
    "WorkflowConfigSchema",
    "StageAssignmentRead",
    "ReviewerCandidateRead",
    "AssignReviewerRequest",
    "ReassignReviewerRequest",
    "ReopenRequestCreate",
    "DirectReopenRequest",
    "ReopenDecisionRequest",
    "ReopenRequestRead",
    "SourceFollowupDecisionRequest",
    "WorkflowTemplateCreate",
    "WorkflowTemplateUpdate",
    "WorkflowTemplateRead",
    "NotificationRead",
    "DiscussionImageRead",
    "DiscussionAudioRead",
    "DiscussionRead",
    "MentionCandidatesRead",
    "DiscussionUpdate",
    "CommentUpdate",
    "EditHistoryRead",
    "RequestUploadParams",
    "RequestTrackUploadParams",
    "PresignedUploadResponse",
    "ConfirmUploadParams",
    "SourceExternalLinkSubmission",
    "ConfirmMasterDeliveryUploadParams",
    "ConfirmSourceFollowupUploadParams",
    "ConfirmTrackUploadParams",
    "RequestCommentAudioUploadParams",
    "PresignedCommentAudioResponse",
    "AppConfigResponse",
]
