"""initial schema

Revision ID: 10fe2b812550
Revises: 
Create Date: 2026-04-06 11:20:04.196256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fe2b812550'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_members_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circle_members_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('master_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_deliveries_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    with op.batch_alter_table('track_source_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_source_versions_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_source_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_source_versions_uploaded_by_id'))

    with op.batch_alter_table('master_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_deliveries_uploaded_by_id'))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_author_id'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))

    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_circle_members_circle_id'))

    # ### end Alembic commands ###
