"""add archived_at to tracks

Revision ID: 31dddf7c1876
Revises: 7853e5c295a4
Create Date: 2026-04-08 22:11:45.669349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31dddf7c1876'
down_revision: Union[str, Sequence[str], None] = '7853e5c295a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tracks_archived_at'), ['archived_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_archived_at'))
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
