"""track bpm to string, add original_title original_artist

Revision ID: 5a044024dc37
Revises: acf97c38424f
Create Date: 2026-04-11 00:11:57.161624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a044024dc37'
down_revision: Union[str, Sequence[str], None] = 'acf97c38424f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('original_artist', sa.String(length=200), nullable=True))
        batch_op.alter_column('bpm',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('bpm',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('original_artist')
        batch_op.drop_column('original_title')

    # ### end Alembic commands ###
