"""add workflow_templates table and album FK

Revision ID: 7853e5c295a4
Revises: g2h3i4j5k6l7
Create Date: 2026-04-08 12:21:07.548699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7853e5c295a4'
down_revision: Union[str, Sequence[str], None] = 'g2h3i4j5k6l7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_config', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_templates_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_templates_id'), ['id'], unique=False)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_album_workflow_template', 'workflow_templates', ['workflow_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint('fk_album_workflow_template', type_='foreignkey')
        batch_op.drop_column('workflow_template_id')

    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_templates_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_templates_circle_id'))

    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
