"""add issue_images table

Revision ID: 968731a990b3
Revises: d251552c23aa
Create Date: 2026-04-11 20:38:07.606396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968731a990b3'
down_revision: Union[str, Sequence[str], None] = 'd251552c23aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_images_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_images_issue_id'))
        batch_op.drop_index(batch_op.f('ix_issue_images_id'))

    op.drop_table('issue_images')
    # ### end Alembic commands ###
