"""add old_status and new_status to comments

Revision ID: bb6e121c61b2
Revises: e2f3a4b5c6d7
Create Date: 2026-04-11 13:41:47.808581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6e121c61b2'
down_revision: Union[str, Sequence[str], None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('new_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('new_status')
        batch_op.drop_column('old_status')

    # ### end Alembic commands ###
