"""add edit history notification album and edited_at

Revision ID: d251552c23aa
Revises: bb6e121c61b2
Create Date: 2026-04-11 16:43:13.569488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd251552c23aa'
down_revision: Union[str, Sequence[str], None] = 'bb6e121c61b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_content', sa.Text(), nullable=False),
    sa.Column('edited_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_histories_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_histories_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_histories_id'), ['id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_album_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_album', 'albums', ['related_album_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('track_discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_discussions', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_album', type_='foreignkey')
        batch_op.drop_column('related_album_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('edit_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_histories_id'))
        batch_op.drop_index(batch_op.f('ix_edit_histories_entity_type'))
        batch_op.drop_index(batch_op.f('ix_edit_histories_entity_id'))

    op.drop_table('edit_histories')
    # ### end Alembic commands ###
