"""add_stage_assignments_reopen_requests_and_delivery_confirmed_at

Revision ID: d7fbf1963f92
Revises: 4ae9fcb746da
Create Date: 2026-04-09 10:20:20.906312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fbf1963f92'
down_revision: Union[str, Sequence[str], None] = '4ae9fcb746da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reopen_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('target_stage_id', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reopen_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reopen_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reopen_requests_track_id'), ['track_id'], unique=False)

    op.create_table('stage_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_assignments_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_assignments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('master_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_deliveries', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    with op.batch_alter_table('stage_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_stage_assignments_track_id'))
        batch_op.drop_index(batch_op.f('ix_stage_assignments_id'))

    op.drop_table('stage_assignments')
    with op.batch_alter_table('reopen_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reopen_requests_track_id'))
        batch_op.drop_index(batch_op.f('ix_reopen_requests_id'))

    op.drop_table('reopen_requests')
    # ### end Alembic commands ###
